package docs

// This file is auto-generated by swag
// To generate the swagger documentation, run:
// swag init -g main.go --output ./docs

// The actual swagger documentation will be generated when you run:
// go install github.com/swaggo/swag/cmd/swag@latest
// swag init
